"""empty message

Revision ID: f32b4cd0bb1b
Revises: 
Create Date: 2021-09-11 19:56:28.186760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f32b4cd0bb1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users_session')
    op.add_column('accounts', sa.Column('url', sa.String(length=32), nullable=True))
    op.drop_index('ix_accounts_site', table_name='accounts')
    op.create_index(op.f('ix_accounts_url'), 'accounts', ['url'], unique=False)
    op.drop_column('accounts', 'site')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('accounts', sa.Column('site', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_accounts_url'), table_name='accounts')
    op.create_index('ix_accounts_site', 'accounts', ['site'], unique=False)
    op.drop_column('accounts', 'url')
    op.create_table('users_session',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('terminal_pid', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('begin', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_session_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='users_session_pkey')
    )
    op.drop_table('sessions')
    # ### end Alembic commands ###
